repos:
- repo: local
  hooks:
    - id: terraform_fmt
      name: Terraform Format
      entry: bash -c 'terraform fmt -recursive >/dev/null'
      language: system
      pass_filenames: false
      stages: [commit]